# Generated by luzgen at 2023-10-17 23:08:06.458281
from luz import Control, Module

# Define control metadata here
control = Control(
	name='RocketNoAlert', 
	id='com.pedromopi.rocketnoalert', 
	version='1.0.0', 
	author='pedromopi', 
	maintainer='pedromopi', 
	depends=[], 
	architecture='iphoneos-arm64'
)

# Module info
modules = [
    Module(
		type='tweak', 
		name='RocketNoAlert', 
		files=['Sources/Tweak.x'], 
		filter={'bundles': ['com.burbn.instagram']}
	)
]